events {
    worker_connections 1024;
}

http {
    include /etc/nginx/conf.d/*.conf;

    server {
        listen 80 default_server;

        location / {
            add_header Content-Type application/json;
            return 200 '{"message": "DevOps Sandbox Platform", "status": "ready"}';
        }
    }
}
